import { Instructor, SingleCourse } from "./app/interfaces";

export const courses: Array<SingleCourse> = [
  {
    id: 1,
    img: "/assets/images/course-1.png",
    name: "Web Development Bootcamp",
    instructorName: "John Smith",
    category: "Development",
    price: 200,
    discount: 50,
    info: {
      duration: "12Week",
      level: "Beginner",
      studentsNum: 1200,
      lessons: 50,
      quizes: 10,
    },
    overview: "Learn full-stack web development from scratch.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/john-smith.jpg",
      desc: "Full-stack developer with 10+ years of experience in web technologies.",
      coursesNum: 12,
      studentsNum: 4500,
      quote: "Code is like humor. When you have to explain it, it’s bad.",
      socialMediaLinks: {
        facebook: "https://facebook.com/johnsmith",
        pinterest: "https://pinterest.com/johnsmith",
        instagram: "https://instagram.com/johnsmith",
        youtube: "https://youtube.com/johnsmith",
      },
    },
    faq: [],
    rating: 4.5,
    reviewersNum: 250,
    fiveStars: 180,
    fourStars: 50,
    threeStars: 15,
    twoStars: 5,
    oneStars: 0,
    reviews: [],
  },
  {
    id: 2,
    img: "/assets/images/course-1.png",
    name: "UI/UX Design Masterclass",
    instructorName: "Emily Johnson",
    category: "Design",
    price: 150,
    discount: 30,
    info: {
      duration: "15Week",
      level: "Intermediate",
      studentsNum: 980,
      lessons: 35,
      quizes: 8,
    },
    overview: "Master UI/UX principles and design beautiful apps.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/emily-johnson.jpg",
      desc: "UI/UX designer passionate about user-centered design and accessibility.",
      coursesNum: 8,
      studentsNum: 3200,
      quote: "Design is not just what it looks like, design is how it works.",
      socialMediaLinks: {
        facebook: "https://facebook.com/emilyjohnson",
        pinterest: "https://pinterest.com/emilyjohnson",
        instagram: "https://instagram.com/emilyjohnson",
        youtube: "https://youtube.com/emilyjohnson",
      },
    },
    faq: [],
    rating: 4.7,
    reviewersNum: 300,
    fiveStars: 220,
    fourStars: 60,
    threeStars: 15,
    twoStars: 5,
    oneStars: 0,
    reviews: [],
  },
  {
    id: 3,
    img: "/assets/images/course-1.png",
    name: "React.js Complete Guide",
    instructorName: "Michael Lee",
    category: "Development",
    price: 180,
    discount: 40,
    info: {
      duration: "10Week",
      level: "Advanced",
      studentsNum: 1100,
      lessons: 45,
      quizes: 9,
    },
    overview: "Dive deep into React with hooks, context, and more.",
    curriculum: [],
    instructorInfo: {
      image: "/assets/images/undraw_education_3vwh.svg",
      desc: "Expert in web development and modern JavaScript frameworks.",
      coursesNum: 12,
      studentsNum: 4500,
      quote: "Code is like humor. When you have to explain it, it’s bad.",
      socialMediaLinks: {
        facebook: "https://facebook.com/michaellee",
        pinterest: "https://pinterest.com/michaellee",
        instagram: "https://instagram.com/michaellee",
        youtube: "https://youtube.com/michaellee",
      },
    },
    faq: [],
    rating: 4.6,
    reviewersNum: 280,
    fiveStars: 200,
    fourStars: 60,
    threeStars: 15,
    twoStars: 5,
    oneStars: 0,
    reviews: [],
  },
  {
    id: 4,
    img: "/assets/images/course-1.png",
    name: "Python for Data Science",
    instructorName: "Sarah Brown",
    category: "Data Science",
    price: 220,
    discount: 60,
    info: {
      duration: "14Week",
      level: "Intermediate",
      studentsNum: 1500,
      lessons: 55,
      quizes: 12,
    },
    overview: "Learn Python for machine learning and data analysis.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/sarah-brown.jpg",
      desc: "Data scientist helping businesses leverage Python for insights.",
      coursesNum: 6,
      studentsNum: 2800,
      quote: "Data is the new oil.",
      socialMediaLinks: {
        facebook: "https://facebook.com/sarahbrown",
        pinterest: "https://pinterest.com/sarahbrown",
        instagram: "https://instagram.com/sarahbrown",
        youtube: "https://youtube.com/sarahbrown",
      },
    },
    faq: [],
    rating: 4.8,
    reviewersNum: 400,
    fiveStars: 320,
    fourStars: 60,
    threeStars: 15,
    twoStars: 5,
    oneStars: 0,
    reviews: [],
  },
  {
    id: 5,
    img: "/assets/images/course-1.png",
    name: "Digital Marketing Essentials",
    instructorName: "David Wilson",
    category: "Marketing",
    price: 130,
    discount: 20,
    info: {
      duration: "6Month",
      level: "Beginner",
      studentsNum: 800,
      lessons: 30,
      quizes: 6,
    },
    overview: "Boost your career with core digital marketing skills.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/david-wilson.jpg",
      desc: "Marketing strategist helping brands grow online.",
      coursesNum: 10,
      studentsNum: 3900,
      quote: "Marketing is really just about sharing your passion.",
      socialMediaLinks: {
        facebook: "https://facebook.com/davidwilson",
        pinterest: "https://pinterest.com/davidwilson",
        instagram: "https://instagram.com/davidwilson",
        youtube: "https://youtube.com/davidwilson",
      },
    },
    faq: [],
    rating: 4.4,
    reviewersNum: 180,
    fiveStars: 120,
    fourStars: 40,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [],
  },
  {
    id: 6,
    img: "/assets/images/course-1.png",
    name: "Photography Fundamentals",
    instructorName: "Sophia Martinez",
    category: "Photography",
    price: 100,
    discount: 15,
    info: {
      duration: "5Month",
      level: "Beginner",
      studentsNum: 600,
      lessons: 25,
      quizes: 5,
    },
    overview: "Learn how to capture stunning photos like a pro.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/sophia-martinez.jpg",
      desc: "Professional photographer sharing tips and techniques.",
      coursesNum: 5,
      studentsNum: 2500,
      quote: "A picture is worth a thousand words.",
      socialMediaLinks: {
        facebook: "https://facebook.com/sophiamartinez",
        pinterest: "https://pinterest.com/sophiamartinez",
        instagram: "https://instagram.com/sophiamartinez",
        youtube: "https://youtube.com/sophiamartinez",
      },
    },
    faq: [],
    rating: 4.3,
    reviewersNum: 150,
    fiveStars: 90,
    fourStars: 40,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [],
  },
  {
    id: 7,
    img: "/assets/images/course-1.png",
    name: "Business Analytics with Excel",
    instructorName: "James Anderson",
    category: "Business",
    price: 170,
    discount: 35,
    info: {
      duration: "40Week",
      level: "Intermediate",
      studentsNum: 720,
      lessons: 40,
      quizes: 7,
    },
    overview: "Analyze business data effectively using Excel tools.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/james-anderson.jpg",
      desc: "Business analyst with expertise in Excel and data visualization.",
      coursesNum: 7,
      studentsNum: 3000,
      quote: "Numbers tell the story.",
      socialMediaLinks: {
        facebook: "https://facebook.com/jamesanderson",
        pinterest: "https://pinterest.com/jamesanderson",
        instagram: "https://instagram.com/jamesanderson",
        youtube: "https://youtube.com/jamesanderson",
      },
    },
    faq: [],
    rating: 4.5,
    reviewersNum: 220,
    fiveStars: 160,
    fourStars: 40,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [],
  },
  {
    id: 8,
    img: "/assets/images/course-1.png",
    name: "3D Modeling with Blender",
    instructorName: "Olivia Taylor",
    category: "Design",
    price: 190,
    discount: 45,
    info: {
      duration: "11Week",
      level: "Advanced",
      studentsNum: 500,
      lessons: 48,
      quizes: 10,
    },
    overview: "Create realistic 3D models and animations in Blender.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/olivia-taylor.jpg",
      desc: "3D artist and designer specializing in Blender modeling and animation.",
      coursesNum: 6,
      studentsNum: 2600,
      quote: "Imagination is the limit.",
      socialMediaLinks: {
        facebook: "https://facebook.com/oliviataylor",
        pinterest: "https://pinterest.com/oliviataylor",
        instagram: "https://instagram.com/oliviataylor",
        youtube: "https://youtube.com/oliviataylor",
      },
    },
    faq: [],
    rating: 4.6,
    reviewersNum: 260,
    fiveStars: 180,
    fourStars: 60,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [],
  },
  {
    id: 9,
    img: "/assets/images/course-1.png",
    name: "Cybersecurity Basics",
    instructorName: "Daniel Clark",
    category: "Security",
    price: 210,
    discount: 55,
    info: {
      duration: "13Week",
      level: "Beginner",
      studentsNum: 900,
      lessons: 52,
      quizes: 11,
    },
    overview: "Understand the fundamentals of cybersecurity.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/daniel-clark.jpg",
      desc: "Cybersecurity expert teaching the fundamentals of online security.",
      coursesNum: 4,
      studentsNum: 2200,
      quote: "Security is a mindset.",
      socialMediaLinks: {
        facebook: "https://facebook.com/danielclark",
        pinterest: "https://pinterest.com/danielclark",
        instagram: "https://instagram.com/danielclark",
        youtube: "https://youtube.com/danielclark",
      },
    },
    faq: [],
    rating: 4.7,
    reviewersNum: 310,
    fiveStars: 230,
    fourStars: 60,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [],
  },
  {
    id: 10,
    img: "/assets/images/course-1.png",
    name: "Mobile App Development with Flutter",
    instructorName: "Sophia White",
    category: "Development",
    price: 195,
    discount: 40,
    info: {
      duration: "30Weeks",
      level: "Intermediate",
      studentsNum: 1050,
      lessons: 47,
      quizes: 9,
    },
    overview: "Build beautiful cross-platform apps with Flutter.",
    curriculum: [],
    instructorInfo: {
      image: "/instructors/sophia-white.jpg",
      desc: "Flutter developer creating cross-platform mobile applications.",
      coursesNum: 5,
      studentsNum: 2500,
      quote: "Build once, run everywhere.",
      socialMediaLinks: {
        facebook: "https://facebook.com/sophiawhite",
        pinterest: "https://pinterest.com/sophiawhite",
        instagram: "https://instagram.com/sophiawhite",
        youtube: "https://youtube.com/sophiawhite",
      },
    },
    faq: [],
    rating: 4.6,
    reviewersNum: 290,
    fiveStars: 210,
    fourStars: 60,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [],
  },
  {
    id: 11,
    img: "/assets/images/course-1.png",
    name: "Node.js Masterclass",
    instructorName: "Daniel Green",
    category: "Backend Development",
    price: 140,
    discount: 119,
    info: {
      duration: "25Weeks",
      studentsNum: 2200,
      lessons: 28,
      quizes: 6,
    },
    overview: "Learn how to build scalable backend applications using Node.js.",
    curriculum: [
      {
        title: "Node.js Basics",
        duration: "50m",
        lessonsNum: 4,
        lessons: [
          { name: "Installing Node.js", duration: "10m" },
          { name: "Modules & NPM", duration: "15m" },
          { name: "Building HTTP Server", duration: "15m" },
          { name: "Async Patterns", duration: "10m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-11.png",
      desc: "Backend engineer with 10 years of experience.",
      coursesNum: 7,
      studentsNum: 14000,
      quote: "Code the server that powers the future.",
      socialMediaLinks: {
        facebook: "https://facebook.com/danielgreen",
        pinterest: "https://pinterest.com/danielgreen",
        instagram: "https://instagram.com/danielgreen",
        youtube: "https://youtube.com/danielgreen",
      },
    },
    faq: [
      {
        question: "Do I need backend experience?",
        answer: "No, but JS basics are required.",
      },
      { question: "Do you cover REST APIs?", answer: "Yes, extensively." },
    ],
    rating: 4.7,
    reviewersNum: 380,
    fiveStars: 280,
    fourStars: 70,
    threeStars: 20,
    twoStars: 5,
    oneStars: 5,
    reviews: [
      {
        image: "/assets/images/user-11.png",
        name: "Marta Rossi",
        content: "Node.js explained simply!",
        date: "2025-01-25",
      },
    ],
  },

  {
    id: 12,
    img: "/assets/images/course-1.png",
    name: "Fullstack with MERN",
    instructorName: "Sophia Brown",
    category: "Web Development",
    price: 180,
    discount: 150,
    info: {
      duration: "30Week",
      studentsNum: 3500,
      lessons: 35,
      quizes: 8,
    },
    overview:
      "Become a fullstack developer with MongoDB, Express, React, and Node.",
    curriculum: [
      {
        title: "Intro to MERN",
        duration: "1h",
        lessonsNum: 5,
        lessons: [
          { name: "What is MERN?", duration: "15m" },
          { name: "MongoDB Basics", duration: "15m" },
          { name: "Express Routing", duration: "15m" },
          { name: "React Setup", duration: "10m" },
          { name: "Node Server", duration: "5m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-12.png",
      desc: "Fullstack mentor and bootcamp instructor.",
      coursesNum: 6,
      studentsNum: 11000,
      quote: "Frontend + Backend = Power.",
      socialMediaLinks: {
        facebook: "https://facebook.com/sophiabrown",
        pinterest: "https://pinterest.com/sophiabrown",
        instagram: "https://instagram.com/sophiabrown",
        youtube: "https://youtube.com/sophiabrown",
      },
    },
    faq: [
      {
        question: "Do you teach deployment?",
        answer: "Yes, including cloud services.",
      },
    ],
    rating: 4.9,
    reviewersNum: 520,
    fiveStars: 450,
    fourStars: 50,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [
      {
        image: "/assets/images/user-12.png",
        name: "Ali Khan",
        content: "Perfect for fullstack beginners!",
        date: "2025-02-05",
      },
    ],
  },

  {
    id: 13,
    img: "/assets/images/course-1.png",
    name: "UI/UX Design Essentials",
    instructorName: "Liam Davis",
    category: "Design",
    price: 130,
    discount: 99,
    info: {
      duration: "18Week",
      studentsNum: 2700,
      lessons: 22,
      quizes: 4,
    },
    overview:
      "Master the principles of user interface and user experience design.",
    curriculum: [
      {
        title: "Design Basics",
        duration: "40m",
        lessonsNum: 3,
        lessons: [
          { name: "Intro to UI/UX", duration: "15m" },
          { name: "Color & Typography", duration: "15m" },
          { name: "Layout Principles", duration: "10m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-13.png",
      desc: "UX Designer with projects at Fortune 500 companies.",
      coursesNum: 4,
      studentsNum: 8000,
      quote: "Design is about solving problems beautifully.",
      socialMediaLinks: {
        facebook: "https://facebook.com/liamdavis",
        pinterest: "https://pinterest.com/liamdavis",
        instagram: "https://instagram.com/liamdavis",
        youtube: "https://youtube.com/liamdavis",
      },
    },
    faq: [
      {
        question: "Do I need Figma?",
        answer: "Yes, we’ll use it throughout the course.",
      },
    ],
    rating: 4.6,
    reviewersNum: 310,
    fiveStars: 200,
    fourStars: 70,
    threeStars: 30,
    twoStars: 5,
    oneStars: 5,
    reviews: [
      {
        image: "/assets/images/user-13.png",
        name: "Hiro Tanaka",
        content: "Very practical examples.",
        date: "2025-03-01",
      },
    ],
  },

  {
    id: 14,
    img: "/assets/images/course-1.png",
    name: "Data Structures & Algorithms",
    instructorName: "Olivia White",
    category: "Computer Science",
    price: 200,
    discount: 170,
    info: {
      duration: "4Month",
      studentsNum: 5000,
      lessons: 45,
      quizes: 10,
    },
    overview:
      "Learn data structures and algorithms to crack coding interviews.",
    curriculum: [
      {
        title: "Arrays and Strings",
        duration: "1h",
        lessonsNum: 6,
        lessons: [
          { name: "Intro to Arrays", duration: "10m" },
          { name: "2D Arrays", duration: "15m" },
          { name: "Strings Manipulation", duration: "15m" },
          { name: "Coding Exercise", duration: "20m" },
          { name: "Big-O Basics", duration: "10m" },
          { name: "Recap", duration: "10m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-14.png",
      desc: "Competitive programmer and CS lecturer.",
      coursesNum: 9,
      studentsNum: 20000,
      quote: "Algorithms are the language of problem solving.",
      socialMediaLinks: {
        facebook: "https://facebook.com/oliviawhite",
        pinterest: "https://pinterest.com/oliviawhite",
        instagram: "https://instagram.com/oliviawhite",
        youtube: "https://youtube.com/oliviawhite",
      },
    },
    faq: [{ question: "Do I need math?", answer: "Basic math is enough." }],
    rating: 4.9,
    reviewersNum: 800,
    fiveStars: 720,
    fourStars: 60,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [
      {
        image: "/assets/images/user-14.png",
        name: "Carlos Mendes",
        content: "Helped me ace interviews.",
        date: "2025-02-10",
      },
    ],
  },

  {
    id: 15,
    img: "/assets/images/course-1.png",
    name: "Python for Data Science",
    instructorName: "Emma Wilson",
    category: "Data Science",
    price: 160,
    discount: 129,
    info: {
      duration: "28Week",
      studentsNum: 4200,
      lessons: 32,
      quizes: 6,
    },
    overview:
      "Learn Python libraries like NumPy, Pandas, and Matplotlib for data analysis.",
    curriculum: [
      {
        title: "Python Basics",
        duration: "50m",
        lessonsNum: 5,
        lessons: [
          { name: "Intro to Python", duration: "10m" },
          { name: "Data Types", duration: "10m" },
          { name: "Functions", duration: "10m" },
          { name: "Libraries Overview", duration: "10m" },
          { name: "Mini Project", duration: "10m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-15.png",
      desc: "Data scientist at a top tech company.",
      coursesNum: 6,
      studentsNum: 13000,
      quote: "Data is the new oil.",
      socialMediaLinks: {
        facebook: "https://facebook.com/emmawilson",
        pinterest: "https://pinterest.com/emmawilson",
        instagram: "https://instagram.com/emmawilson",
        youtube: "https://youtube.com/emmawilson",
      },
    },
    faq: [
      {
        question: "Do I need Python knowledge?",
        answer: "No, we cover it from basics.",
      },
    ],
    rating: 4.8,
    reviewersNum: 500,
    fiveStars: 400,
    fourStars: 70,
    threeStars: 20,
    twoStars: 5,
    oneStars: 5,
    reviews: [
      {
        image: "/assets/images/user-15.png",
        name: "Fatima Noor",
        content: "Very clear explanations!",
        date: "2025-02-20",
      },
    ],
  },

  {
    id: 16,
    img: "/assets/images/course-1.png",
    name: "Machine Learning A-Z",
    instructorName: "James Miller",
    category: "AI & ML",
    price: 190,
    discount: 159,
    info: {
      duration: "35Week",
      studentsNum: 4800,
      lessons: 38,
      quizes: 9,
    },
    overview:
      "Understand machine learning models and build ML projects from scratch.",
    curriculum: [
      {
        title: "Supervised Learning",
        duration: "1h",
        lessonsNum: 5,
        lessons: [
          { name: "Linear Regression", duration: "15m" },
          { name: "Logistic Regression", duration: "15m" },
          { name: "Decision Trees", duration: "15m" },
          { name: "Random Forest", duration: "10m" },
          { name: "SVM", duration: "15m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-16.png",
      desc: "ML researcher and practitioner.",
      coursesNum: 8,
      studentsNum: 17000,
      quote: "Machines learn, but humans lead.",
      socialMediaLinks: {
        facebook: "https://facebook.com/jamesmiller",
        pinterest: "https://pinterest.com/jamesmiller",
        instagram: "https://instagram.com/jamesmiller",
        youtube: "https://youtube.com/jamesmiller",
      },
    },
    faq: [
      {
        question: "Is coding required?",
        answer: "Yes, Python experience is needed.",
      },
    ],
    rating: 4.7,
    reviewersNum: 670,
    fiveStars: 500,
    fourStars: 120,
    threeStars: 30,
    twoStars: 10,
    oneStars: 10,
    reviews: [
      {
        image: "/assets/images/user-16.png",
        name: "George Park",
        content: "Super practical course!",
        date: "2025-03-02",
      },
    ],
  },

  {
    id: 17,
    img: "/assets/images/course-1.png",
    name: "Cloud Computing with AWS",
    instructorName: "Sophia Turner",
    category: "Cloud",
    price: 150,
    discount: 120,
    info: {
      duration: "22Week",
      studentsNum: 2600,
      lessons: 26,
      quizes: 5,
    },
    overview: "Learn AWS services and deploy applications on the cloud.",
    curriculum: [
      {
        title: "AWS Basics",
        duration: "45m",
        lessonsNum: 4,
        lessons: [
          { name: "Intro to AWS", duration: "15m" },
          { name: "IAM & Security", duration: "10m" },
          { name: "S3 Storage", duration: "10m" },
          { name: "EC2 Instances", duration: "10m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-17.png",
      desc: "AWS certified cloud architect.",
      coursesNum: 5,
      studentsNum: 9000,
      quote: "The future is cloud-powered.",
      socialMediaLinks: {
        facebook: "https://facebook.com/sophiaturner",
        pinterest: "https://pinterest.com/sophiaturner",
        instagram: "https://instagram.com/sophiaturner",
        youtube: "https://youtube.com/sophiaturner",
      },
    },
    faq: [
      {
        question: "Do I need prior cloud knowledge?",
        answer: "No, we start from basics.",
      },
    ],
    rating: 4.6,
    reviewersNum: 300,
    fiveStars: 210,
    fourStars: 60,
    threeStars: 20,
    twoStars: 5,
    oneStars: 5,
    reviews: [
      {
        image: "/assets/images/user-17.png",
        name: "Julia Ivanova",
        content: "Hands-on AWS labs!",
        date: "2025-02-22",
      },
    ],
  },

  {
    id: 18,
    img: "/assets/images/course-1.png",
    name: "Cybersecurity Fundamentals",
    instructorName: "Robert Hall",
    category: "Cybersecurity",
    price: 170,
    discount: 140,
    info: {
      duration: "24Week",
      studentsNum: 3100,
      lessons: 28,
      quizes: 6,
    },
    overview:
      "Protect systems and networks by learning essential cybersecurity skills.",
    curriculum: [
      {
        title: "Security Basics",
        duration: "40m",
        lessonsNum: 4,
        lessons: [
          { name: "Intro to Cybersecurity", duration: "10m" },
          { name: "Network Security", duration: "10m" },
          { name: "Threats & Vulnerabilities", duration: "10m" },
          { name: "Best Practices", duration: "10m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-18.png",
      desc: "Ethical hacker and security consultant.",
      coursesNum: 6,
      studentsNum: 12000,
      quote: "Security is a mindset, not a tool.",
      socialMediaLinks: {
        facebook: "https://facebook.com/roberthall",
        pinterest: "https://pinterest.com/roberthall",
        instagram: "https://instagram.com/roberthall",
        youtube: "https://youtube.com/roberthall",
      },
    },
    faq: [
      {
        question: "Do I need IT experience?",
        answer: "Basic IT knowledge helps.",
      },
    ],
    rating: 4.7,
    reviewersNum: 450,
    fiveStars: 320,
    fourStars: 100,
    threeStars: 20,
    twoStars: 5,
    oneStars: 5,
    reviews: [
      {
        image: "/assets/images/user-18.png",
        name: "Ahmed Salah",
        content: "Clear and informative.",
        date: "2025-02-28",
      },
    ],
  },

  {
    id: 19,
    img: "/assets/images/course-1.png",
    name: "React Native Mobile Apps",
    instructorName: "Chloe Martin",
    category: "Mobile Development",
    price: 150,
    discount: 120,
    info: {
      duration: "20Week",
      studentsNum: 2700,
      lessons: 24,
      quizes: 5,
    },
    overview: "Build cross-platform mobile apps using React Native.",
    curriculum: [
      {
        title: "React Native Basics",
        duration: "50m",
        lessonsNum: 5,
        lessons: [
          { name: "Setup & Tools", duration: "10m" },
          { name: "Components", duration: "10m" },
          { name: "Navigation", duration: "10m" },
          { name: "State Management", duration: "10m" },
          { name: "Mini Project", duration: "10m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-19.png",
      desc: "Mobile app developer with multiple published apps.",
      coursesNum: 5,
      studentsNum: 10000,
      quote: "Learn once, deploy everywhere.",
      socialMediaLinks: {
        facebook: "https://facebook.com/chloemartin",
        pinterest: "https://pinterest.com/chloemartin",
        instagram: "https://instagram.com/chloemartin",
        youtube: "https://youtube.com/chloemartin",
      },
    },
    faq: [
      {
        question: "Do I need JS knowledge?",
        answer: "Yes, basic JS is needed.",
      },
    ],
    rating: 4.8,
    reviewersNum: 400,
    fiveStars: 320,
    fourStars: 60,
    threeStars: 15,
    twoStars: 3,
    oneStars: 2,
    reviews: [
      {
        image: "/assets/images/user-19.png",
        name: "Sara Lee",
        content: "Great for building real apps!",
        date: "2025-03-05",
      },
    ],
  },

  {
    id: 20,
    img: "/assets/images/course-1.png",
    name: "Docker & Kubernetes",
    instructorName: "Ethan Scott",
    category: "DevOps",
    price: 180,
    discount: 145,
    info: {
      duration: "26Week",
      studentsNum: 2900,
      lessons: 30,
      quizes: 6,
    },
    overview: "Containerize applications and orchestrate them efficiently.",
    curriculum: [
      {
        title: "Docker Essentials",
        duration: "45m",
        lessonsNum: 4,
        lessons: [
          { name: "Intro to Docker", duration: "10m" },
          { name: "Images & Containers", duration: "10m" },
          { name: "Docker Compose", duration: "10m" },
          { name: "Mini Project", duration: "15m" },
        ],
        isLocked: false,
      },
    ],
    instructorInfo: {
      image: "/assets/images/instructor-20.png",
      desc: "DevOps engineer with enterprise experience.",
      coursesNum: 7,
      studentsNum: 15000,
      quote: "Containers simplify everything.",
      socialMediaLinks: {
        facebook: "https://facebook.com/ethanscott",
        pinterest: "https://pinterest.com/ethanscott",
        instagram: "https://instagram.com/ethanscott",
        youtube: "https://youtube.com/ethanscott",
      },
    },
    faq: [
      {
        question: "Do I need prior Docker experience?",
        answer: "No, basics covered.",
      },
    ],
    rating: 4.6,
    reviewersNum: 350,
    fiveStars: 250,
    fourStars: 70,
    threeStars: 20,
    twoStars: 5,
    oneStars: 5,
    reviews: [
      {
        image: "/assets/images/user-20.png",
        name: "Ivan Petrov",
        content: "Perfect intro to containerization.",
        date: "2025-03-07",
      },
    ],
  },
];
